[33mcommit 8c31dad76541493f017b76fa26340fdb7d601105[m
Author: Devon Kristine Zuegel <devonzuegel@gmail.com>
Date:   Mon Jul 14 13:20:16 2014 -0700

    basic photo uploader works

A	data/journal/prealloc.2
A	local.0
A	local.ns
A	mongod.lock
A	node_modules/blueimp-file-upload-expressjs/.npmignore
A	node_modules/blueimp-file-upload-expressjs/.travis.yml
A	node_modules/blueimp-file-upload-expressjs/README.md
A	node_modules/blueimp-file-upload-expressjs/index.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/.bin/jasmine-node
A	node_modules/blueimp-file-upload-expressjs/node_modules/.bin/jasmine-node.cmd
A	node_modules/blueimp-file-upload-expressjs/node_modules/.bin/mkdirp
A	node_modules/blueimp-file-upload-expressjs/node_modules/.bin/mkdirp.cmd
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/.eslintrc
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/.gitignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/.travis.yml
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/.yardopts
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/.yardopts_guide
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/CONTRIBUTING.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/Gemfile
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/Gemfile.lock
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/LICENSE.txt
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/NOTICE.txt
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/Rakefile
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/UPGRADING.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/bower.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/configuration.sample
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist-tools/.eslintrc
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist-tools/browser-builder.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist-tools/strategies/cache.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist-tools/strategies/default.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist-tools/test/browser-builder.mocha.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist-tools/test/helpers.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist/BUNDLE_LICENSE.txt
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist/aws-sdk.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/dist/aws-sdk.min.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/browser-building.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/browser-configuring-wif.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/browser-configuring.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/browser-examples.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/browser-intro.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/browser-making-requests.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/browser-services.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/index.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/node-configuring.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/node-examples.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/node-intro.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/node-making-requests.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/guide/node-services.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/model_documentor.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/plugin.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/class/html/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/class/html/waiter_details_list.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/class/html/waiter_summary.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/docstring/html/experimental.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/docstring/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/fulldoc/html/css/common.css
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/fulldoc/html/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/layout/html/services.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/layout/html/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/module/html/box_info.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/module/html/children.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/tags/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/waiter_details/html/method_signature.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/api-versions/templates/default/waiter_details/html/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/default/layout/html/footer.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/default/layout/html/layout.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/css/highlight.github.css
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/css/style.css
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/img/logo.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/js/app.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/js/highlight.pack.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/js/sphinx/AUTHORS
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/js/sphinx/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/js/sphinx/doctools.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/js/sphinx/file.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/js/sphinx/searchtools.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/js/underscore.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/search.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/search_index.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/fulldoc/html/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/layout/html/layout.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/layout/html/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/layout/html/sidebar.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/onefile/html/layout.erb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/doc-src/templates/flasky_sphinx_guide/onefile/html/setup.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/eslint-rules/no-require-in-service.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/autoscaling/autoscaling.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/autoscaling/step_definitions/autoscaling.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudformation/cloudformation.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudformation/step_definitions/cloudformation.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudfront/cloudfront.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudfront/step_definitions/cloudfront-latest.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudfront/step_definitions/cloudfront.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudsearch/cloudsearch.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudsearch/step_definitions/cloudsearch.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudtrail/cloudtrail.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudtrail/step_definitions/cloudtrail.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudwatch/cloudwatch.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudwatch/step_definitions/cloudwatch.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudwatchlogs/cloudwatchlogs.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cloudwatchlogs/step_definitions/cloudwatchlogs.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cognitoidentity/cognitoidentity.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cognitoidentity/step_definitions/cognitoidentity.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cognitosync/cognitosync.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/cognitosync/step_definitions/cognitosync.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/datapipeline/datapipeline.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/datapipeline/step_definitions/datapipeline.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/directconnect/directconnect.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/directconnect/step_definitions/directconnect.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/dynamodb/crc32.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/dynamodb/step_definitions/dynamodb.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/dynamodb/tables.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/ec2/ec2.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/ec2/step_definitions/ec2.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/elasticache/elasticache.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/elasticache/step_definitions/elasticache.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/elasticbeanstalk/elasticbeanstalk.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/elasticbeanstalk/step_definitions/elasticbeanstalk.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/elastictranscoder/elastictranscoder.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/elastictranscoder/step_definitions/elastictranscoder.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/elb/elb.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/elb/step_definitions/elb.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/emr/emr.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/emr/step_definitions/emr.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/extra/assertions.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/extra/dummy.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/extra/fixtures/testfile.txt
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/extra/helpers.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/extra/hooks.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/extra/world.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/glacier/glacier.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/glacier/step_definitions/glacier.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/iam/iam.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/iam/step_definitions/iam.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/importexport/importexport.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/importexport/step_definitions/importexport.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/kinesis/kinesis.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/kinesis/step_definitions/kinesis.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/opsworks/opsworks.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/opsworks/step_definitions/opsworks.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/rds/rds.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/rds/step_definitions/rds.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/redshift/redshift.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/redshift/step_definitions/redshift.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/route53/route53.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/route53/step_definitions/route53.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/s3/buckets.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/s3/objects.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/s3/step_definitions/buckets.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/s3/step_definitions/hooks.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/s3/step_definitions/objects.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/s3/step_definitions/proxy.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/ses/ses.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/ses/step_definitions/ses.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/simpledb/simpledb.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/simpledb/step_definitions/simpledb.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sns/sns.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sns/step_definitions/sns.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sqs/messages.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sqs/queues.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sqs/step_definitions/messages.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sqs/step_definitions/queues.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sqs/step_definitions/sqs.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/storagegateway/step_definitions/storagegateway.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/storagegateway/storagegateway.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sts/step_definitions/sts.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/sts/sts.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/support/step_definitions/support.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/support/support.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/swf/step_definitions/swf.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/features/swf/swf.feature
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/index.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/aws.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/browser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/config.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/core.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials/ec2_metadata_credentials.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials/environment_credentials.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials/file_system_credentials.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials/saml_credentials.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials/temporary_credentials.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/credentials/web_identity_credentials.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/event_listeners.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/http.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/http/node.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/http/xhr.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/json/builder.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/json/parser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/metadata_service.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/model/api.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/model/collection.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/model/operation.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/model/paginator.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/model/resource_waiter.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/model/shape.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/param_validator.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/protocol/json.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/protocol/query.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/protocol/rest.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/protocol/rest_json.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/protocol/rest_xml.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/query/query_param_serializer.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/region_config.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/region_config.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/request.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/resource_waiter.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/response.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/sequential_executor.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/service.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/cloudsearchdomain.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/cognitoidentity.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/dynamodb.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/ec2.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/elastictranscoder.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/glacier.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/route53.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/s3.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/sqs.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/sts.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/services/swf.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/signers/presign.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/signers/request_signer.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/signers/s3.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/signers/v2.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/signers/v3.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/signers/v3https.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/signers/v4.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/state_machine.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/util.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/xml/browser_parser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/xml/builder.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/lib/xml/node_parser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/package.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/scripts/console
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/tasks/apis.rake
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/tasks/browser.rake
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/tasks/docs.rake
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/tasks/lib/cucumber_generator.rb
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/tasks/util.rake
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/jasmine-2.0.0/MIT.LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/jasmine-2.0.0/boot.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/jasmine-2.0.0/console.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/jasmine-2.0.0/jasmine-html.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/jasmine-2.0.0/jasmine.css
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/jasmine-2.0.0/jasmine.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/runner.html
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/runner.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/appinfo.sample.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/console.html
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/animated-overlay.gif
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-bg_glass_75_dadada_1x400.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-icons_222222_256x240.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-icons_2e83ff_256x240.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-icons_454545_256x240.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-icons_888888_256x240.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/images/ui-icons_cd0a0a_256x240.png
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/jquery-ui-1.10.1.custom.css
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/css/smoothness/jquery-ui-1.10.1.custom.min.css
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/img/loading.gif
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/js/jquery-1.9.1.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/js/jquery-ui-1.10.1.custom.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/js/jquery-ui-1.10.1.custom.min.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/browser/sample/s3upload.html
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/config.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/credential_provider_chain.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/credentials.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/endpoint.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/event_listeners.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/helpers.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/http_request.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/json/builder.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/json/parser.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/metadata_service.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/mocha.opts
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/model/api.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/model/shape.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/node_http_client.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/param_validator.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/protocol/json.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/protocol/query.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/protocol/rest.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/protocol/rest_json.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/protocol/rest_xml.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/query/query_param_serializer.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/region_config.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/request.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/resource_waiter.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/response.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/sequential_executor.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/service.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/cloudfront.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/cloudsearchdomain.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/dynamodb.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/ec2.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/elastictranscoder.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/glacier.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/rds.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/route53.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/s3.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/simpledb.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/sqs.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/sts.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/services/swf.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/signers/presign.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/signers/s3.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/signers/v2.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/signers/v4.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/util.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/xml/builder.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/test/xml/parser.spec.coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/aws-sdk/testem.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/.travis.yml
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/Readme.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/index.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/lib/file.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/lib/incoming_form.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/lib/index.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/lib/json_parser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/lib/multipart_parser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/lib/octet_parser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/lib/querystring_parser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/formidable/package.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/.travis.yml
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/bin/jasmine-node
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/bower.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/async-callback.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/autotest.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/cli.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/cs.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/index.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/jasmine-1.3.1.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/reporter.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/requirejs-runner.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/requirejs-spec-loader.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/requirejs-wrapper-template.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/lib/jasmine-node/spec-collection.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/.bin/cake
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/.bin/cake.cmd
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/.bin/coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/.bin/coffee.cmd
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/.bin/r.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/.bin/r.js.cmd
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/CNAME
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/CONTRIBUTING.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/README
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/bin/cake
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/bin/coffee
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/browser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/cake.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/coffee-script.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/command.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/grammar.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/helpers.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/index.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/lexer.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/nodes.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/optparse.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/parser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/register.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/repl.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/rewriter.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/scope.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/lib/coffee-script/sourcemap.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/package.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/coffee-script/register.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/.editorconfig
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/.jshintrc
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/.travis.yml
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/AUTHORS
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/Gruntfile.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/LICENSE-MIT
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/benchmarks/gaze100s.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/lib/gaze.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/.travis.yml
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/LICENSE-MIT
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/lib/fileset.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/.travis.yml
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/examples/g.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/examples/usr-local.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/glob.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/inherits/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/inherits/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/inherits/inherits.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/inherits/inherits_browser.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/inherits/package.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/inherits/test.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/minimatch.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/.npmignore
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/CONTRIBUTORS
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/lib/lru-cache.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/package.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/test/basic.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/test/foreach.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/lru-cache/test/memory-leak.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/sigmund/LICENSE
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/sigmund/README.md
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/sigmund/bench.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/sigmund/package.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/sigmund/sigmund.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/node_modules/sigmund/test/basic.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/package.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/test/basic.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/test/brace-expand.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/test/caching.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/test/defaults.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/node_modules/minimatch/test/extglob-ending-with-state-char.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/package.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/00-setup.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/bash-comparison.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/bash-results.json
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/cwd-test.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/globstar-match.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/mark.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/new-glob-optional-options.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/nocase-nomagic.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/pause-resume.js
A	node_modules/blueimp-file-upload-expressjs/node_modules/jasmine-node/node_modules/gaze/node_modules/fileset/node_modules/glob/test/readme-issu